services:
  mantle:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: mantle
    restart: unless-stopped
    ports:
      - "3001:8080"
    volumes:
      - /root/frontend/open-webui:/app/backend/data
      - ./bg.png:/app/backend/open_webui/static/bg.png
    networks:
      - homelab_network
    environment:
      - WEBUI_NAME=MANTLE
      - WEBUI_SECRET_KEY=abcdgdgsouwqiouehfnjshauit1y2ohjyouyoji21
      - WEBUI_URL=https://n8n.corgi-catla.ts.net:8443
      - DATABASE_URL=postgresql://postgres:Limj3579@db:5432/openwebui
      - ENABLE_SIGNUP=True
      - DEFAULT_USER_ROLE=user
      - ENABLE_RAG_OCR=True
      - CONTENT_EXTRACTION_ENGINE=pypdfium2
      - MANTLE_SHOW_ADVANCED_SETTINGS=Connections,Models,Evaluations,Documents,Web Search,Interface

networks:
  homelab_network:
    external: true
